[window]
padding = { x = 15, y = 15 }
opacity = 0.80
decorations = "None"

[font]
size = 11.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

# This is the magic line that links to Pywal
import = ["~/.cache/wal/colors-alacritty.toml"]

[env]
TERM = "xterm-256color"
