[window]
padding = { x = 15, y = 15 }
opacity = 0.85
decorations = "None"
[font]
size = 11.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
[colors.primary]
background = "#1E1E1E"
foreground = "#D8DEE9"
[env]
TERM = "xterm-256color"
